apiVersion: v1
kind: Service

metadata:
  name: cloud-native-service
  labels:
    app: cloud-native-app

spec:
  type: LoadBalancer

  selector:
    app: cloud-native-app

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000